name = "QuantumFCS"
uuid = "f61df7d1-40df-4ff5-bdc9-ea200d60bc8f"
authors = ["aarondanielphysics <aaron.danie> and marcelojbp <marcelobro.pera@gmail.com>"]
version = "1.0.0-DEV"

[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

#optional dependency
[weakdeps]
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"

[extensions]
QuantumFCSQuantumOpticsExt = "QuantumOptics"   # loads if QuantumOptics is present

[compat]
julia = "1.9, 1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
